src/components/common/Navbar/index.tsx, src/components/common/Navbar/styles.ts, src/styles/globalStyle.ts
- Link를 NavLink 변경
- 사원 연차 관리 추가
- 글로벌 스타일 line-height 수정
=> ✨ NavLink로 변경 사원 연차 관리 추가

src/apis/instance.ts
axios instance 파일을 폼 데이터 전송을 위한 세팅으로 인해 수정하였습니다.
=> 🔧 폼 데이터 전송을 위한 세팅

src/apis/instance.ts
axios instance 파일 수정했고 msw 구동도 확인했습니다
=> 🔧 axios instance 파일 수정

package.json, src/apis/auth.ts, src/components/ApplicationPage/ApplyCalendar/index.tsx, src/components/ApplicationPage/ApplyInfo/index.tsx, src/components/common/Alarm/index.tsx, src/components/common/Alarm/styles.ts, src/components/common/Navbar/index.tsx, src/components/common/Navbar/styles.ts, src/hooks/useGetSchedule.ts, src/interfaces/common.ts, src/store/index.ts, src/store/reducers/alarmReducers.ts, src/store/reducers/userReducers.ts, yarn.lock
- customButtons 및 이전/다음 버튼 클릭 시 실행되는 함수 삭제
- useGetSchedules에 현재 년-월 보내지 않음
- axios 함수 url 및 매개변수 수정
- 연차 신청 버튼 활성화
- 잔여 연차 일수보다 많은 날짜 선택 불가
- 현재 날짜보다 이전의 날짜 클릭 시 sweetalert 처리
=> 🔧 연차/당직 가져오기 API 수정에 따른 훅 및 함수 수정

src/apis/auth.ts, src/components/UserMainPage/ApplicationStatus/index.tsx, src/components/UserMainPage/ApplicationStatus/styles.ts, src/components/UserMainPage/index.tsx, src/components/ViewSchedulePage/ViewSchedule/index.tsx, src/components/ViewSchedulePage/ViewSchedule/styles.ts, src/components/common/Header/index.tsx, src/components/common/ScheduleCalendar/index.tsx, src/components/common/ScheduleCalendar/styles.ts, src/hooks/useGetSchedule.ts, src/interfaces/application.ts, src/interfaces/common.ts, src/pages/ViewSchedulePage/index.tsx
헤더
* refetch 버튼 구현 (유저 직급에 따라 요청하는 쿼리 함수 다르게 처리 예정)
신청 현황
* 취소시 더블체크 모달 구현
* 취소시 이미 승인 또는 거절 되었다면 이에 대한 모달 구현
=> ✨ 유저메인 페이지

src/apis/auth.ts, src/pages/LoginPage/index.tsx
=> 🔧 로그인 실패 조건 통합

src/apis/auth.ts, src/hooks/useLogin.ts, src/store/reducers/userReducers.ts
=> ✨ loginUserData Store에 저장 구현

src/apis/auth.ts, src/components/ApplicationPage/ApplyCalendar/index.tsx, src/components/common/Alarm/AlarmCard/index.tsx, src/hooks/useVerifyToken.ts, src/routes/ProtectedRouter.tsx, src/routes/Router.tsx, src/store/reducers/userReducers.ts, src/utils/userTokenCookie.ts
- 백엔드 측 인증 api 미구현으로, 액세스 토큰/리프레시 토큰 유효성 검사 실행 못함
- 대신 로그인하면 store에 user 개인정보가 저장되는 것을 이용해 store에 userId가 있는지 없는지 확인 후 홈 화면으로 넘어가도록 설계
- 백엔드 측과 협의 후 추후 토큰 유효성 검사로 수정할 예정. 일단 기능 구현하는데 있어서 어려움은 없어보임
[전달사항]
- store에 user 개인정보가 저장되는 로직과 헤더에 accessToken 세팅 되는 구조가 구현되었으니, 이제 포스트맨 사용 안하셔도 됩니다! 목업으로 진행했던 부분 수정해주세요~!
=> ✨ ProtectedRouter 구현

src/App.tsx, src/apis/auth.ts, src/components/UserMainPage/ApplicationStatus/index.tsx, src/components/UserMainPage/index.tsx, src/components/ViewSchedulePage/ViewSchedule/index.tsx, src/components/common/Header/index.tsx, src/hooks/useGetSchedule.ts, src/pages/HomePage/index.tsx
HomePage 컴포넌트
* 로그인한 유저의 직급에 따라 다른 페이지 렌더링
Header 컴포넌트
* 로그인한 유저의 직급에 따른 refetch 버튼 기능 구현
유저 메인 페이지 
* 로그인한 유저의 신청 현황 및 남은 연차 일
내 일정 보기 페이지
* 로그인한 유저의 일정 렌더링
=> 유저 메인 페이지, 내 일정 보기, 캘린더 수정

netlify.toml, src/App.tsx, src/apis/auth.ts, src/components/common/Alarm/AlarmCard/index.tsx, src/components/common/Alarm/AlarmCard/styles.ts, src/components/common/Alarm/index.tsx, src/components/common/Alarm/styles.ts, src/components/common/Navbar/index.tsx, src/interfaces/alarm.ts, src/store/reducers/userReducers.ts
#41 
- 관리자/일반 유저 알림 내용 다르게 세팅
- 알림 목록에서 날짜 표시 유틸 함수 사용
- 배포를 위한 리다이렉트 수정
- 연차/당직 신청 시 에러 처리
- 알림 버튼 눌러서 알림 닫을 때에도 store에 최신 정보 저장
=> 🐛 관리자용 알림 구현 및 에러 수정

src/components/common/Navbar/index.tsx, src/components/common/Navbar/styles.ts, src/pages/HomePage/admin/styles.ts
- 로그아웃 시 쿠키 지우기
- 프로필 이미지 꽉차게
- 네비바에 사원 연차 관리 사원에게 안보이게
=> ✨ 로그아웃 시 쿠키 삭제, 프로필 이미지 수정, Navbar 수정

src/App.tsx, src/apis/auth.ts, src/components/ApplicationPage/ApplyCalendar/index.tsx, src/components/ApplicationPage/ApplyInfo/index.tsx, src/components/common/Alarm/AlarmCard/index.tsx, src/components/common/Alarm/AlarmCard/styles.ts, src/components/common/Alarm/index.tsx, src/components/common/Layout/index.tsx, src/components/common/Layout/styles.ts, src/components/common/Loading/index.tsx, src/components/common/Loading/styles.ts, src/components/common/Navbar/index.tsx, src/components/common/ScheduleCalendar/styles.ts, src/hooks/useGetNewAlarms.ts, src/hooks/useGetSchedule.ts, src/hooks/useVerifyToken.ts, src/interfaces/alarm.ts, src/routes/ProtectedRouter.tsx, src/store/index.ts, src/store/reducers/userReducers.ts, src/styles/globalStyle.ts, src/utils/cookies.ts
- 타입스크립트 에러 수정
- 테스트용 코드 삭제
- 알람 리스트 출력 문제
- 알람 보여주는 방식 수정 (새로운 알람 + 이전 알람)
- diffDays 관련 에러 수정 (하루 더 많게 선택되는 문제)
- axios 함수 try catch 문 사용
- redux-persist serializableCheck 처리
=> 🐛 버그 리스트 해결

src/apis/admin.ts, src/components/AdminHomePage/ApplicationStatus/index.tsx
- 연차 / 당직 신청 현황 에러 팝업 추가
- ♻️  react-query 수정
- ♻️ 주석 지움
=> ✨ 연차 / 당직 신청 현황 에러 팝업 추가 및 리팩토링

src/components/common/Navbar/index.tsx, src/components/common/Navbar/styles.ts
=> 💄 username, tag 부분 style 변경

src/components/common/Navbar/index.tsx
=> ✨ SSE 연결 함수 heartTimeout 기능 설정

src/pages/LoginPage/styles.ts, src/pages/SignupPage/index.tsx, src/pages/SignupPage/styles.ts
- 스크롤 되지 않도록 각 부모 요소 height:100vh 설정
- 배너 이미지는 width:auto; height:100% 설정
=> 💄 로그인, 회원가입 페이지 스타일 수정

src/hooks/useLogin.ts
=> ✨ 로그인 실패시 Swal 기능 추가

src/components/UserMainPage/index.tsx, src/interfaces/application.ts
=> 🐛 타입스크립트 관련 에러 수정

src/components/common/Navbar/index.tsx, src/hooks/useGetNewAlarms.ts
=> :bug: 버튼 누를 때 useGetNewAlarms 재실행되지 않는 문제 해결

src/components/UserMainPage/ApplicationStatus/index.tsx
이미 승인/거절된 신청 취소시 현황에 바로 반영되도록 수정
=> 🐛 이미 승인/거절된 신청 취소시 현황에 바로 반영되도록 수정

src/hooks/useSignup.ts, src/pages/SignupPage/index.tsx
=> :recycle: 안쓰는 코드 삭제
